version: '3.4'

services:
  app:
    build: .
    command: >
      sh -c "
        rm -f tmp/pids/server.pid &&
        bundle install &&
        yarn install &&
        rails server -b 0.0.0.0
      "
    volumes:
      - ./:/app
    ports:
      - "3000:3000" # Mapea el puerto 3000 del contenedor al 3000 de la máquina host
    environment:
      - RAILS_ENV=development # Define el entorno de Rails
